# Default Values
port = 7497
date = "20250110"
host = "127.0.0.1"
data_type = 4
instrument = "SPX"
exchange = "CBOE"
currency = "USD"

# Changeable Values
number_of_re_entry = 2
OTM_CALL_HEDGE = 10
OTM_PUT_HEDGE = 10
ATM_CALL = 2
ATM_PUT = 2
call_sl = 15
put_sl = 15
conversion_time = 10
entry_hour = 9
entry_minute = 35
entry_second = 0
exit_hour = 15
exit_minute = 45
exit_second = 0
call_hedge_quantity = 1
put_hedge_quantity = 1
call_position = 1
put_position = 1
